### ISSUE TITLE
ValueError: Namespace GConf not available

### ISSUE THREAD

**Issue by aasutossh** [mwahlroos/Nautiterm#1] opened 2020-02-12 03:18 UTC
I did the apt installation, and did the copying of the file.
Got following error:
```
Failed to load module "appmenu-gtk-module"
Traceback (most recent call last):
  File "/home/aasutossh/.local/share/nautilus-python/extensions/open_terminal.py", line 23, in <module>
    gi.require_version('GConf', '2.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GConf not available
```

**Comment by mwahlroos** [comment] 2020-04-15 23:47
Hi, and thank you for your report.

I'm not primarily using Ubuntu myself, so this issue may have slipped through. I'll try to find out what the problem is and how to fix it, though.

Also, sorry about the delay. This project is pretty much about scratching my own itch, and I didn't expect any attention to it, so I didn't notice your report until now.

**Comment by aasutossh** [comment] 2020-04-16 03:11
It's alright. Maybe the `Gconf` mean `gconf-editor` or something? I didn't have `gconf-editor` installed at that time. Just a wild guess. 

Also I am using `Filemanager-Actions` for this purpose. If you don't have much time, you can ignore/close this issue.
Take care.

**Comment by mwahlroos** [comment] 2020-04-16 14:22
Should be fixed by https://github.com/mwahlroos/Nautiterm/commit/47f920a1c2a07d59aca59da20b23c255bb324f1f.

**Closed as completed by mwahlroos** 2020-04-16 14:22 UTC

**Comment by LorenzoMorelli** [comment] 2021-02-02 17:43
I resolved installing "gconf" with: `sudo apt install gir1.2-gconf-2.0`
It works great!!

**Comment by mwahlroos** [comment] 2021-02-02 18:28
@LorenzoMorelli
Glad that you got it working. However, that should no longer be necessary, as there's no dependency on GConf anymore.

Either way, if it works for you as it is, that's great!

**Comment by LorenzoMorelli** [comment] 2021-02-02 18:36
@mwahlroos I'm using ubuntu 20.04, I don't have investigated but that give me that error until installing that package.
However I want to thank you so much, that was what I looking for.
Nice coding!!
